name: CI/CD - React App

on:
  push:
    branches: [main, deploy]
  pull_request:
    branches: [main, deploy]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test -- --watchAll=false

      - name: Construir la aplicación
        run: npm run build
